version: "3.9"
   
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=insecure
      - POSTGRES_PASSWORD=insecure
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: