# Generated by Django 3.2.9 on 2021-12-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attatchedFile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
