# Generated by Django 3.2.9 on 2021-11-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
