# Generated by Django 3.2.9 on 2021-12-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachedFile',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
